# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  minikube.delete:
    cmds:
      - minikube delete

  minikube.configure:
    cmds:
      - minikube config set cpus 4
      - minikube config set memory 10240

  minikube.start:
    deps: [minikube.configure]
    cmds:
      - minikube start